add EntityVersion
MarcRaeder/Book-REST-API pull request #1
Opened 2022-11-16 12:51 UTC by MarcRaeder

add RestAPI with Microsoft.EntityFramework

2022-11-16 17:04 UTC, stefanluth requested changes
Delete generated files and create a single `.gitignore` in the root dir :D

2022-11-17 07:42 UTC, DevBastiS requested changes
What Stefan said :D

2022-11-21 08:48 UTC, DevBastiS requested changes
Still 550 Files changed.
Add the bin folder to gitignore as well.

2022-11-21 09:25 UTC, stefanluth reviewed
Add EOFs :)

2022-11-21 12:40 UTC, stefanluth requested changes
just code style and imports :)

2022-11-21 12:40 UTC, stefanluth commented on BookApi/BookApi/Controllers/BookController1.cs
> +using BookApi.Service;
Some unused `usings`. Also, the file is named `BookController1.cs` :D Remove the `1`

2022-11-21 12:40 UTC, stefanluth commented on BookApi/BookApi/Service/BookService.cs
> +using NuGet.Protocol.Core.Types;
Unused `using`

2022-11-21 12:40 UTC, stefanluth commented on BookApi/BookApi/Repository/BookRepository.cs
> +}
```suggestion
        await bookContext.SaveChangesAsync();

        return bookToUpdate;
    }

}
```

2022-11-21 12:40 UTC, stefanluth commented on BookApi/BookApi/Service/BookService.cs
> +    public async Task<Book> UpdatePageCountOfBook(string title, int newPageCount)
```suggestion
    }

    public async Task<IList<Book>> DeleteAllBooks()
    {
        return await bookRepository.DeleteAllBooks();
    }

    public async Task<Book> UpdatePageCountOfBook(string title, int newPageCount)
```

2022-11-21 12:40 UTC, stefanluth commented on BookApi/BookApi/Models/Book.cs
> +    public int? PageCount { get; set; }
```suggestion
    public Guid Id { get; set; }

    [Required]
    public string Title { get; set; }

    public int? PageCount { get; set; }
```

2022-11-21 12:40 UTC, stefanluth commented on BookApi/BookApi/Controllers/BookController1.cs
> +        [HttpPost("createBook")]
```suggestion
        }

        [HttpPost("createBook")]

```

2022-11-23 07:08 UTC, DevBastiS requested changes

2022-11-23 07:08 UTC, DevBastiS commented on BookApi/BookApi/Controllers/BookController1.cs
> +    public class BookController1 : ControllerBase
```suggestion
    public class BookController : ControllerBase

```

2022-11-23 07:08 UTC, DevBastiS commented on BookApi/BookApi/Program.cs
> +// Add services to the container.
Remove comments

2022-11-23 07:08 UTC, DevBastiS commented on BookApi/BookApi/Repository/BookRepository.cs
> +using BookApi.Models;
usings should be inside/below the namespace

2022-11-23 07:08 UTC, DevBastiS commented on BookApi/BookApi/Repository/BookRepository.cs
> +            Console.WriteLine(e);
If you are only writing the error to the console and then throwing it again you can work without the try catch.

2022-11-23 07:08 UTC, DevBastiS commented on BookApi/BookApi/Repository/BookRepository.cs
> +            .Where(book => book.Title == title)
You should work with primary key "id" here. The title could return more then one result.

2022-11-23 07:08 UTC, DevBastiS commented on BookApi/BookApi/Service/BookService.cs
> +    private BookRepository bookRepository;
```suggestion
    private BookRepository BookRepository;
```

2023-01-03 13:00 UTC, MarcRaeder commented on BookApi/BookApi/Repository/BookRepository.cs
> +using BookApi.Models;
if i place the usings under namespace i get errormessages

2023-01-04 15:28 UTC, stefanluth commented on BookApi/BookApi/Controllers/BookController.cs
> +        [HttpPut("updatePageCountOfBook")]
Use all lowercase and api routes and connect multiple words with hyphens :)
e.g.
`get-all-books`

2023-01-04 15:28 UTC, stefanluth commented on BookApi/BookApi/Program.cs
> +using Microsoft.Extensions.Hosting;
```suggestion
using Microsoft.EntityFrameworkCore;
```

VSCode shows these as unused imports :)

2023-01-04 15:28 UTC, stefanluth commented on BookApi/BookApi/Service/BookService.cs
> +using BookApi.Models;
```suggestion
using BookApi.Models;
```
VSCode shows these as unused imports :)

2023-01-04 15:28 UTC, stefanluth commented on BookApi/BookApi/Repository/BookRepository.cs
> +using Microsoft.EntityFrameworkCore;
```suggestion
using BookApi.Models;
using Microsoft.EntityFrameworkCore;
```
VSCode shows these as unused imports :)

2023-01-04 15:28 UTC, stefanluth commented on BookApi/BookApi/Models/Book.cs
> +using System;
```suggestion
```

2023-01-04 15:28 UTC, stefanluth commented on BookApi/BookApi/Controllers/BookController.cs
> +using BookApi.Service;
```suggestion
using Microsoft.AspNetCore.Mvc;
using BookApi.Models;
using BookApi.Service;

```

2023-01-09 13:08 UTC, stefanluth approved these changes

2023-01-10 12:08 UTC, DevBastiS approved these changes

2023-01-10 13:02 UTC, merged